
BLENDER="C:\Program Files\Blender Foundation\Blender 2.91\blender.exe"
DIST=../dist

all : \
    $(DIST)/glitch.pnct \
    $(DIST)/glitch.scene \

$(DIST)/glitch.scene : glitch.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "glitch.blend:Collection" "$(DIST)/glitch.scene"

$(DIST)/glitch.pnct : glitch.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "glitch.blend:Collection" "$(DIST)/glitch.pnct" 
